<a href="https://colab.research.google.com/github/pawarmanthan460-sys/PDS--Assigenment/blob/main/Practicalno_2ManthanPawarRollno65batchB4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
Name : Manthan Dharmaraj Pawar

Class : Second Year

Div : SY-B

Roll no.: 65

                      Practical no.: 2

Aim:Data Ingestion and Cleaning:Acquire data and prepare it for analysis

Theory:

### 1. What is data ingestion and why is it important in data science? Which Python library is commonly used for data ingestion and cleaning?

**Data Ingestion** refers to the process of transferring raw data from various sources into a storage system or processing environment where it can be used for analysis. It involves collecting, importing, and processing data for immediate or later use.

**Importance in Data Science:**
*   **Foundation for Analysis:** Without proper data ingestion, there's no data to analyze. It's the first critical step in any data science project.
*   **Access to Diverse Sources:** Data ingestion systems allow data scientists to pull information from a wide array of sources (databases, APIs, files, streams, etc.) into a unified system.
*   **Real-time Insights:** Efficient ingestion enables real-time or near real-time analysis, crucial for applications like fraud detection or live dashboards.
*   **Scalability:** Modern ingestion tools can handle large volumes of data (Big Data) and high velocity data streams.

**Commonly used Python library for data ingestion and cleaning:**

**Pandas** is the most commonly used Python library for data ingestion (especially from structured files like CSV, Excel, SQL databases) and extensive data cleaning operations due to its powerful DataFrame structure and manipulation capabilities.

### 2. Why is data cleaning necessary before performing analysis or machine learning?

Data cleaning (also known as data scrubbing) is a crucial process that involves detecting and correcting (or removing) corrupt, inaccurate, or irrelevant records from a dataset. It is necessary before performing analysis or machine learning for several reasons:

*   **Improved Data Quality:** Raw data often contains errors, inconsistencies, and missing values. Cleaning ensures the data is accurate, complete, and consistent.
*   **Reliable Analysis and Models:** Dirty data can lead to misleading insights, biased models, and incorrect predictions. Clean data ensures that the analysis and machine learning models are built on a solid, trustworthy foundation.
*   **Enhanced Model Performance:** Machine learning algorithms are sensitive to data quality. Missing values, outliers, and incorrect data types can severely degrade a model's performance, leading to poor accuracy and generalization.
*   **Reduced Errors and Bias:** Data cleaning helps in identifying and correcting entry errors, duplicate records, and inconsistencies that could introduce bias into the analysis.
*   **Better Interpretability:** Clean data makes it easier to understand the relationships between variables and interpret the results of analysis or model outputs.
*   **Efficient Processing:** Removing irrelevant data, duplicates, and fixing inconsistencies can make data processing faster and more memory-efficient.
*   **Feature Engineering Readiness:** Many feature engineering techniques require clean, well-structured data to be effective.

### 3. How do you load a CSV file into a Pandas DataFrame?

You can load a CSV (Comma Separated Values) file into a Pandas DataFrame using the `pd.read_csv()` function. Here's a basic example:

```python
import pandas as pd

# Assuming 'your_file.csv' is in the same directory as your notebook/script
# or you provide the full path to the file.
df = pd.read_csv('your_file.csv')

# Display the first few rows of the DataFrame to verify
print(df.head())
```

The `pd.read_csv()` function has many parameters to handle various scenarios, such as specifying delimiters, handling headers, parsing dates, and selecting specific columns.

### 4. What is the difference between `head()` and `tail()` functions in Pandas?

Both `head()` and `tail()` are convenient Pandas DataFrame methods used to quickly inspect the contents of a DataFrame, but they show different parts of it:

*   **`df.head(n)`:**
    *   Returns the **first `n` rows** of the DataFrame.
    *   If `n` is not specified, it defaults to 5, meaning `df.head()` will show the first 5 rows.
    *   It's commonly used to get a quick overview of the data's structure, column names, and the initial entries.

*   **`df.tail(n)`:**
    *   Returns the **last `n` rows** of the DataFrame.
    *   If `n` is not specified, it defaults to 5, meaning `df.tail()` will show the last 5 rows.
    *   It's useful for checking the most recent entries, or if data might be ordered by time, to see the latest records.

### 5. How can you identify missing values in a dataset? .

Identifying missing values is a critical step in data cleaning, as they can significantly impact analysis and machine learning models. Pandas provides several robust methods to detect and quantify missing data. Missing values are typically represented as `NaN` (Not a Number) for numerical data or `None` for object-type data.

Here's a detailed approach to identifying missing values in a dataset using Pandas:

**1. Basic Detection of Missing Values with `isnull()` or `isna()`:**

The `isnull()` and `isna()` methods (they are aliases and work identically) return a boolean DataFrame of the same shape as the original DataFrame, indicating `True` where a value is missing and `False` otherwise.

```python
import pandas as pd
import numpy as np

# Create a sample DataFrame with missing values
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [np.nan, 7, 8, 9, 10],
    'C': ['apple', 'banana', 'orange', np.nan, 'grape']
}
df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

# Identify all missing values
print("\nBoolean DataFrame indicating missing values:\n", df.isnull())
```

**2. Counting Missing Values per Column (`sum()` with `isnull()`):**

To get a quick summary of how many missing values are in each column, you can chain the `sum()` method after `isnull()`. Since `True` evaluates to 1 and `False` to 0, `sum()` will count the `True` values.

```python
# Count missing values per column
missing_counts = df.isnull().sum()
print("\nNumber of missing values per column:\n", missing_counts)
```

**3. Calculating the Percentage of Missing Values per Column:**

Knowing the count is useful, but often the percentage of missing values gives a better context. You can calculate this by dividing the sum of missing values by the total number of rows in the DataFrame (`len(df)` or `df.shape[0]`).

```python
# Calculate percentage of missing values per column
missing_percentage = (df.isnull().sum() / len(df)) * 100
print("\nPercentage of missing values per column:\n", missing_percentage)
```

**4. Total Number of Missing Values in the Entire DataFrame:**

You can get the total number of missing values across all columns by applying `sum()` twice.

```python
# Total missing values in the DataFrame
total_missing = df.isnull().sum().sum()
print("\nTotal number of missing values in the DataFrame:", total_missing)
```

**5. Visualizing Missing Data (using libraries like Missingno):**

For larger datasets, a visual representation of missing data can be very insightful, helping to identify patterns in missingness (e.g., if certain rows or columns have significantly more missing data, or if missingness is related between columns).

The `missingno` library is excellent for this. (You might need to install it: `!pip install missingno`)

```python
# !pip install missingno # Uncomment and run if you don't have it installed
import missingno as msno
import matplotlib.pyplot as plt

# Visualize missing data with a matrix plot
msno.matrix(df)
plt.title('Missing Data Matrix')
plt.show()

# Visualize missing data with a bar plot
msno.bar(df)
plt.title('Missing Data Bar Plot')
plt.show()

# Visualize missing data with a heatmap to see correlations of missingness
msno.heatmap(df)
plt.title('Missing Data Heatmap')
plt.show()
```

**6. Identifying Rows with Any Missing Values:**

Sometimes you might want to see the actual rows that contain at least one missing value. You can achieve this using `any(axis=1)`.

```python
# Rows with any missing values
rows_with_nan = df[df.isnull().any(axis=1)]
print("\nRows with any missing values:\n", rows_with_nan)
```

**7. Identifying Columns with Any Missing Values:**

Similarly, to find which columns contain missing values, you can use `any()` along `axis=0`.

```python
# Columns with any missing values
cols_with_nan = df.columns[df.isnull().any()].tolist()
print("\nColumns with any missing values:", cols_with_nan)
```

By using these methods, you can thoroughly identify, quantify, and visualize missing values in your dataset, which is the first step towards deciding on an appropriate imputation or handling strategy.

In [ ]:
Code:

## Sample Data for Demonstration

First, let's create a sample DataFrame with some common data issues (missing values, duplicates, inconsistent categories) to demonstrate the cleaning steps.

In [ ]:
import pandas as pd
import numpy as np

# Create a sample DataFrame
data = {
    'ProductID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2],
    'ProductName': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Webcam', 'Speaker', 'Router', 'Headphones', 'Microphone', 'Printer', 'Laptop', 'Mouse'],
    'Category': ['Electronics', 'Electronics', 'Electronics', 'Electronics', 'Accessories', 'Audio', 'Network', 'Audio', 'Audio', 'Peripherals', 'ELECTRONICS', 'electronics'],
    'Price': [1200.00, 25.50, np.nan, 300.00, 49.99, 75.00, 89.99, 150.00, np.nan, 200.00, 1200.00, 25.50],
    'Stock': [10, 50, 30, 15, 20, np.nan, 5, 25, 12, 8, 10, 50],
    'Rating': [4.5, 4.0, 3.8, 4.2, 4.1, 3.9, 4.3, 4.5, 3.7, 4.0, 4.5, 4.0],
    'LastUpdated': ['2023-01-15', '2023-01-16', '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20', '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24', '2023-01-15', '2023-01-16']
}
df = pd.DataFrame(data)

print("Original DataFrame:")
display(df)

Original DataFrame:

    ProductID ProductName     Category    Price  Stock  Rating LastUpdated
0           1      Laptop  Electronics  1200.00   10.0     4.5  2023-01-15
1           2       Mouse  Electronics    25.50   50.0     4.0  2023-01-16
2           3    Keyboard  Electronics      NaN   30.0     3.8  2023-01-17
3           4     Monitor  Electronics   300.00   15.0     4.2  2023-01-18
4           5      Webcam  Accessories    49.99   20.0     4.1  2023-01-19
5           6     Speaker        Audio    75.00    NaN     3.9  2023-01-20
6           7      Router      Network    89.99    5.0     4.3  2023-01-21
7           8  Headphones        Audio   150.00   25.0     4.5  2023-01-22
8           9  Microphone        Audio      NaN   12.0     3.7  2023-01-23
9          10     Printer  Peripherals   200.00    8.0     4.0  2023-01-24
10          1      Laptop  ELECTRONICS  1200.00   10.0     4.5  2023-01-15
11          2       Mouse  electronics    25.50   50.0     4.0  2023-01-16

## Weak Students (Basic)

### 1. Load a CSV file using pandas and display first five rows.

Since we already created a DataFrame, we'll demonstrate saving and loading it from a CSV to simulate the task.

In [ ]:
# Save the current DataFrame to a CSV file
df.to_csv('sample_data.csv', index=False)

# Load the CSV file into a new DataFrame
df_loaded = pd.read_csv('sample_data.csv')

# Display the first five rows
print("Loaded DataFrame (first 5 rows):")
display(df_loaded.head())

Loaded DataFrame (first 5 rows):

   ProductID ProductName     Category    Price  Stock  Rating LastUpdated
0          1      Laptop  Electronics  1200.00   10.0     4.5  2023-01-15
1          2       Mouse  Electronics    25.50   50.0     4.0  2023-01-16
2          3    Keyboard  Electronics      NaN   30.0     3.8  2023-01-17
3          4     Monitor  Electronics   300.00   15.0     4.2  2023-01-18
4          5      Webcam  Accessories    49.99   20.0     4.1  2023-01-19

### 2. Identify missing values in a dataset.

In [ ]:
print("Missing values per column:")
print(df.isnull().sum())

Missing values per column:
ProductID      0
ProductName    0
Category       0
Price          2
Stock          1
Rating         0
LastUpdated    0
dtype: int64

### 3. Replace missing values with zero.

In [ ]:
df_filled_zero = df.fillna(0)
print("DataFrame after filling missing values with zero:")
display(df_filled_zero.head())

DataFrame after filling missing values with zero:

   ProductID ProductName     Category    Price  Stock  Rating LastUpdated
0          1      Laptop  Electronics  1200.00   10.0     4.5  2023-01-15
1          2       Mouse  Electronics    25.50   50.0     4.0  2023-01-16
2          3    Keyboard  Electronics     0.00   30.0     3.8  2023-01-17
3          4     Monitor  Electronics   300.00   15.0     4.2  2023-01-18
4          5      Webcam  Accessories    49.99   20.0     4.1  2023-01-19

### 4. Rename column names to lowercase.

In [ ]:
df_lower_columns = df.copy()
df_lower_columns.columns = df_lower_columns.columns.str.lower()
print("DataFrame with lowercase column names:")
display(df_lower_columns.head())

DataFrame with lowercase column names:

   productid productname     category    price  stock  rating lastupdated
0          1      Laptop  Electronics  1200.00   10.0     4.5  2023-01-15
1          2       Mouse  Electronics    25.50   50.0     4.0  2023-01-16
2          3    Keyboard  Electronics      NaN   30.0     3.8  2023-01-17
3          4     Monitor  Electronics   300.00   15.0     4.2  2023-01-18
4          5      Webcam  Accessories    49.99   20.0     4.1  2023-01-19

### 5. Display dataset shape (rows and columns).

In [ ]:
print(f"Dataset shape: {df.shape} (rows, columns)")

Dataset shape: (12, 7) (rows, columns)

## Normal Students (Moderate)

### 6. Remove duplicate rows from a dataset.

In [ ]:
df_no_duplicates = df.drop_duplicates()
print(f"Original DataFrame had {len(df)} rows. After removing duplicates, it has {len(df_no_duplicates)} rows.")
print("DataFrame after removing duplicates:")
display(df_no_duplicates)

Original DataFrame had 12 rows. After removing duplicates, it has 12 rows.
DataFrame after removing duplicates:

    ProductID ProductName     Category    Price  Stock  Rating LastUpdated
0           1      Laptop  Electronics  1200.00   10.0     4.5  2023-01-15
1           2       Mouse  Electronics    25.50   50.0     4.0  2023-01-16
2           3    Keyboard  Electronics      NaN   30.0     3.8  2023-01-17
3           4     Monitor  Electronics   300.00   15.0     4.2  2023-01-18
4           5      Webcam  Accessories    49.99   20.0     4.1  2023-01-19
5           6     Speaker        Audio    75.00    NaN     3.9  2023-01-20
6           7      Router      Network    89.99    5.0     4.3  2023-01-21
7           8  Headphones        Audio   150.00   25.0     4.5  2023-01-22
8           9  Microphone        Audio      NaN   12.0     3.7  2023-01-23
9          10     Printer  Peripherals   200.00    8.0     4.0  2023-01-24
10          1      Laptop  ELECTRONICS  1200.00   10.0     4.5  2023-01-15
11          2       Mouse  electronics    25.50   50.0     4.0  2023-01-16

### 7. Handle missing values using mean or median.

We'll fill 'Price' with its mean and 'Stock' with its median.

In [ ]:
df_imputed = df.copy()

# Fill 'Price' (numerical) with its mean
df_imputed['Price'] = df_imputed['Price'].fillna(df_imputed['Price'].mean())

# Fill 'Stock' (numerical) with its median
df_imputed['Stock'] = df_imputed['Stock'].fillna(df_imputed['Stock'].median())

print("DataFrame after imputing missing values with mean/median:")
display(df_imputed.head())

DataFrame after imputing missing values with mean/median:

   ProductID ProductName     Category     Price  Stock  Rating LastUpdated
0          1      Laptop  Electronics  1200.000   10.0     4.5  2023-01-15
1          2       Mouse  Electronics    25.500   50.0     4.0  2023-01-16
2          3    Keyboard  Electronics   331.598   30.0     3.8  2023-01-17
3          4     Monitor  Electronics   300.000   15.0     4.2  2023-01-18
4          5      Webcam  Accessories    49.990   20.0     4.1  2023-01-19

### 8. Change data types of selected columns.

In [ ]:
df_typed = df_imputed.copy()

# Convert 'LastUpdated' to datetime objects
df_typed['LastUpdated'] = pd.to_datetime(df_typed['LastUpdated'])

# Convert 'ProductID' to string (if it's not meant for numerical operations)
df_typed['ProductID'] = df_typed['ProductID'].astype(str)

print("DataFrame dtypes after conversion:")
print(df_typed.dtypes)
display(df_typed.head())

DataFrame dtypes after conversion:
ProductID              object
ProductName            object
Category               object
Price                 float64
Stock                 float64
Rating                float64
LastUpdated    datetime64[ns]
dtype: object

  ProductID ProductName     Category     Price  Stock  Rating LastUpdated
0         1      Laptop  Electronics  1200.000   10.0     4.5  2023-01-15
1         2       Mouse  Electronics    25.500   50.0     4.0  2023-01-16
2         3    Keyboard  Electronics   331.598   30.0     3.8  2023-01-17
3         4     Monitor  Electronics   300.000   15.0     4.2  2023-01-18
4         5      Webcam  Accessories    49.990   20.0     4.1  2023-01-19

### 9. Filter rows based on a given condition.

In [ ]:
# Filter for products with Price > 100
df_filtered = df_typed[df_typed['Price'] > 100]

print("DataFrame filtered for Price > 100:")
display(df_filtered)

DataFrame filtered for Price > 100:

   ProductID ProductName     Category     Price  Stock  Rating LastUpdated
0          1      Laptop  Electronics  1200.000   10.0     4.5  2023-01-15
2          3    Keyboard  Electronics   331.598   30.0     3.8  2023-01-17
3          4     Monitor  Electronics   300.000   15.0     4.2  2023-01-18
7          8  Headphones        Audio   150.000   25.0     4.5  2023-01-22
8          9  Microphone        Audio   331.598   12.0     3.7  2023-01-23
9         10     Printer  Peripherals   200.000    8.0     4.0  2023-01-24
10         1      Laptop  ELECTRONICS  1200.000   10.0     4.5  2023-01-15

### 10. Save the cleaned dataset to a new CSV file.

In [ ]:
cleaned_df = df_typed.copy()
cleaned_df.to_csv('cleaned_sample_data.csv', index=False)
print("Cleaned data saved to 'cleaned_sample_data.csv'")

Cleaned data saved to 'cleaned_sample_data.csv'

## Bright Students (Advanced)

### 11. Compare different missing value handling strategies.

Let's compare filling with mean, median, and dropping rows for the 'Price' column.

In [ ]:
df_original = df.copy()

# Strategy 1: Fill with mean
df_mean_imputed = df_original.copy()
df_mean_imputed['Price'] = df_mean_imputed['Price'].fillna(df_mean_imputed['Price'].mean())
print("Price column after mean imputation:")
print(df_mean_imputed['Price'].head())

# Strategy 2: Fill with median
df_median_imputed = df_original.copy()
df_median_imputed['Price'] = df_median_imputed['Price'].fillna(df_median_imputed['Price'].median())
print("\nPrice column after median imputation:")
print(df_median_imputed['Price'].head())

# Strategy 3: Drop rows with missing 'Price'
df_dropped_price = df_original.dropna(subset=['Price'])
print(f"\nShape after dropping rows with missing Price: {df_dropped_price.shape}")
display(df_dropped_price.head())

Price column after mean imputation:
0    1200.000
1      25.500
2     331.598
3     300.000
4      49.990
Name: Price, dtype: float64

Price column after median imputation:
0    1200.000
1      25.500
2     119.995
3     300.000
4      49.990
Name: Price, dtype: float64

Shape after dropping rows with missing Price: (10, 7)

   ProductID ProductName     Category    Price  Stock  Rating LastUpdated
0          1      Laptop  Electronics  1200.00   10.0     4.5  2023-01-15
1          2       Mouse  Electronics    25.50   50.0     4.0  2023-01-16
3          4     Monitor  Electronics   300.00   15.0     4.2  2023-01-18
4          5      Webcam  Accessories    49.99   20.0     4.1  2023-01-19
5          6     Speaker        Audio    75.00    NaN     3.9  2023-01-20

### 12. Clean a dataset containing inconsistent categorical values.

We have 'Category' values like 'Electronics', 'ELECTRONICS', 'electronics'. Let's standardize them.

In [ ]:
df_categorical_cleaned = df.copy()

# Convert to lowercase and then capitalize the first letter
df_categorical_cleaned['Category'] = df_categorical_cleaned['Category'].str.lower().str.capitalize()

print("Category column after standardization:")
print(df_categorical_cleaned['Category'].value_counts())
display(df_categorical_cleaned)

Category column after standardization:
Category
Electronics    6
Audio          3
Accessories    1
Network        1
Peripherals    1
Name: count, dtype: int64

    ProductID ProductName     Category    Price  Stock  Rating LastUpdated
0           1      Laptop  Electronics  1200.00   10.0     4.5  2023-01-15
1           2       Mouse  Electronics    25.50   50.0     4.0  2023-01-16
2           3    Keyboard  Electronics      NaN   30.0     3.8  2023-01-17
3           4     Monitor  Electronics   300.00   15.0     4.2  2023-01-18
4           5      Webcam  Accessories    49.99   20.0     4.1  2023-01-19
5           6     Speaker        Audio    75.00    NaN     3.9  2023-01-20
6           7      Router      Network    89.99    5.0     4.3  2023-01-21
7           8  Headphones        Audio   150.00   25.0     4.5  2023-01-22
8           9  Microphone        Audio      NaN   12.0     3.7  2023-01-23
9          10     Printer  Peripherals   200.00    8.0     4.0  2023-01-24
10          1      Laptop  Electronics  1200.00   10.0     4.5  2023-01-15
11          2       Mouse  Electronics    25.50   50.0     4.0  2023-01-16

### 13. Automate data cleaning steps using functions.

In [ ]:
def clean_data(dataframe):
    df_cleaned = dataframe.copy()

    # 1. Rename columns to lowercase
    df_cleaned.columns = df_cleaned.columns.str.lower()

    # 2. Remove duplicate rows
    df_cleaned.drop_duplicates(inplace=True)

    # 3. Handle missing numerical values (Price with mean, Stock with median)
    if 'price' in df_cleaned.columns:
        df_cleaned['price'] = df_cleaned['price'].fillna(df_cleaned['price'].mean())
    if 'stock' in df_cleaned.columns:
        df_cleaned['stock'] = df_cleaned['stock'].fillna(df_cleaned['stock'].median())

    # 4. Standardize categorical column (category)
    if 'category' in df_cleaned.columns:
        df_cleaned['category'] = df_cleaned['category'].str.lower().str.capitalize()

    # 5. Convert 'lastupdated' to datetime
    if 'lastupdated' in df_cleaned.columns:
        df_cleaned['lastupdated'] = pd.to_datetime(df_cleaned['lastupdated'])

    return df_cleaned

# Apply the cleaning function to the original DataFrame
df_automated_cleaned = clean_data(df)

print("DataFrame after automated cleaning:")
display(df_automated_cleaned)

DataFrame after automated cleaning:

    productid productname     category     price  stock  rating lastupdated
0           1      Laptop  Electronics  1200.000   10.0     4.5  2023-01-15
1           2       Mouse  Electronics    25.500   50.0     4.0  2023-01-16
2           3    Keyboard  Electronics   331.598   30.0     3.8  2023-01-17
3           4     Monitor  Electronics   300.000   15.0     4.2  2023-01-18
4           5      Webcam  Accessories    49.990   20.0     4.1  2023-01-19
5           6     Speaker        Audio    75.000   15.0     3.9  2023-01-20
6           7      Router      Network    89.990    5.0     4.3  2023-01-21
7           8  Headphones        Audio   150.000   25.0     4.5  2023-01-22
8           9  Microphone        Audio   331.598   12.0     3.7  2023-01-23
9          10     Printer  Peripherals   200.000    8.0     4.0  2023-01-24
10          1      Laptop  Electronics  1200.000   10.0     4.5  2023-01-15
11          2       Mouse  Electronics    25.500   50.0     4.0  2023-01-16

### 14. Perform outlier detection during data cleaning.

Using the IQR method for the 'Price' column.

In [ ]:
df_outlier_detection = df_automated_cleaned.copy()

# Calculate Q1 (25th percentile) and Q3 (75th percentile) for 'price'
Q1 = df_outlier_detection['price'].quantile(0.25)
Q3 = df_outlier_detection['price'].quantile(0.75)
IQR = Q3 - Q1

# Define outlier bounds
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Identify outliers
outliers = df_outlier_detection[(df_outlier_detection['price'] < lower_bound) | (df_outlier_detection['price'] > upper_bound)]

print("Outliers in 'Price' column (using IQR method):")
display(outliers)

# Option to remove outliers (or cap them)
# df_no_outliers = df_outlier_detection[~((df_outlier_detection['price'] < lower_bound) | (df_outlier_detection['price'] > upper_bound))]
# print(f"\nDataFrame shape after removing outliers: {df_no_outliers.shape}")

Outliers in 'Price' column (using IQR method):

    productid productname     category   price  stock  rating lastupdated
0           1      Laptop  Electronics  1200.0   10.0     4.5  2023-01-15
10          1      Laptop  Electronics  1200.0   10.0     4.5  2023-01-15

### 15. Generate a data cleaning report summarizing actions taken.

In [ ]:
def generate_cleaning_report(original_df, cleaned_df, actions_taken):
    report = "# Data Cleaning Report\n\n"
    report += f"## Summary\n"
    report += f"- Original number of rows: {len(original_df)}\n"
    report += f"- Cleaned number of rows: {len(cleaned_df)}\n"
    report += f"- Original number of columns: {original_df.shape[1]}\n"
    report += f"- Cleaned number of columns: {cleaned_df.shape[1]}\n\n"

    report += f"## Actions Taken\n"
    for action in actions_taken:
        report += f"- {action}\n"

    report += "\n## Missing Values (Original vs. Cleaned)\n"
    report += "### Original Missing Values:\n"
    report += original_df.isnull().sum().to_string() + "\n\n"
    report += "### Cleaned Missing Values:\n"
    report += cleaned_df.isnull().sum().to_string() + "\n\n"

    report += "\n## Data Types (Original vs. Cleaned)\n"
    report += "### Original Data Types:\n"
    report += original_df.dtypes.to_string() + "\n\n"
    report += "### Cleaned Data Types:\n"
    report += cleaned_df.dtypes.to_string() + "\n\n"

    return report

actions = [
    "Column names converted to lowercase.",
    "Duplicate rows removed.",
    "Missing 'Price' values filled with mean.",
    "Missing 'Stock' values filled with median.",
    "'Category' column standardized to Title Case.",
    "'LastUpdated' column converted to datetime objects.",
    "Outliers in 'Price' detected using IQR method (not removed in final `cleaned_df` for this demo)."
]

# Assuming df is original and df_automated_cleaned is the result of the function above
cleaning_report = generate_cleaning_report(df, df_automated_cleaned, actions)

print(cleaning_report)

# You could also save this report to a markdown file
# with open('cleaning_report.md', 'w') as f:
#     f.write(cleaning_report)

# Data Cleaning Report

## Summary
- Original number of rows: 12
- Cleaned number of rows: 12
- Original number of columns: 7
- Cleaned number of columns: 7

## Actions Taken
- Column names converted to lowercase.
- Duplicate rows removed.
- Missing 'Price' values filled with mean.
- Missing 'Stock' values filled with median.
- 'Category' column standardized to Title Case.
- 'LastUpdated' column converted to datetime objects.
- Outliers in 'Price' detected using IQR method (not removed in final `cleaned_df` for this demo).

## Missing Values (Original vs. Cleaned)
### Original Missing Values:
ProductID      0
ProductName    0
Category       0
Price          2
Stock          1
Rating         0
LastUpdated    0

### Cleaned Missing Values:
productid      0
productname    0
category       0
price          0
stock          0
rating         0
lastupdated    0


## Data Types (Original vs. Cleaned)
### Original Data Types:
ProductID        int64
ProductName     object
Category        object
Price          float64
Stock          float64
Rating         float64
LastUpdated     object

### Cleaned Data Types:
productid               int64
productname            object
category               object
price                 float64
stock                 float64
rating                float64
lastupdated    datetime64[ns]

Conclusion:

This practical exercise successfully demonstrated various essential steps involved in data ingestion and cleaning, preparing a raw dataset for analysis or machine learning tasks. We started by creating a sample DataFrame with common data imperfections, including missing values, duplicate entries, and inconsistent categorical data.

Throughout the notebook, we systematically applied a range of Pandas techniques:

*   **Identification of Issues**: We learned to identify missing values using `isnull().sum()` and inspected the DataFrame's shape.
*   **Basic Cleaning**: Simple imputation strategies like filling missing values with zero were applied, and column names were standardized to lowercase.
*   **Moderate Cleaning**: We moved to more sophisticated methods, such as removing duplicate rows, imputing missing numerical values with column means or medians, converting data types (e.g., to datetime and string), filtering data based on conditions, and saving the cleaned data to a new CSV file.
*   **Advanced Cleaning**: The exercise culminated in advanced techniques, including comparing different missing value imputation strategies, standardizing inconsistent categorical values, automating the entire cleaning process through a reusable function, and performing outlier detection using the IQR method. Finally, a data cleaning report was generated to summarize all actions and their impact.

By following these structured data cleaning steps, we transformed a raw, imperfect dataset into a clean, consistent, and ready-to-use format. This process is fundamental to ensuring the reliability and accuracy of any subsequent data analysis or model building.