<a href="https://colab.research.google.com/github/pawarmanthan460-sys/PDS--Assigenment/blob/main/Practical_no3_ManthanPawarRollno65batchB4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
Name : Manthan Dharmaraj Pawar

Class : Second Year

Div : SY-B

Roll no.: 65

                            Practical no.: 3

Aim : Data Wrangling with pandas: Manipulate and transform data to suit the analysis needs

Theory:

1. What is data wrangling, and why is it important before analysis?

**Data wrangling**, also known as data munging or data preparation, is the process of cleaning, structuring, and enriching raw data into a more suitable format for analysis. It involves several steps, including data collection, data exploration, data cleaning, data transformation, and data validation.

**Importance before analysis:**

*   **Ensures Data Quality:** Raw data often contains errors, inconsistencies, and missing values. Wrangling helps to identify and correct these issues, leading to more accurate and reliable analysis results.
*   **Improves Data Usability:** By structuring and transforming data, it becomes easier to work with and understand, allowing analysts to apply various analytical techniques and models effectively.
*   **Enhances Analysis Accuracy:** High-quality, well-prepared data reduces the risk of biases and misleading conclusions, leading to more robust and trustworthy insights.
*   **Saves Time and Effort:** While wrangling can be time-consuming initially, it prevents significant delays and errors during the analysis phase, ultimately saving time and effort.
*   **Facilitates Data Integration:** When combining data from multiple sources, wrangling helps to standardize formats, units, and definitions, enabling seamless integration and comprehensive analysis.
*   **Supports Machine Learning Models:** Machine learning algorithms are highly sensitive to data quality. Wrangling is crucial for creating features, handling outliers, and ensuring that the data is in a format suitable for model training and evaluation.

### 2. You receive messy data with missing values, duplicates, and wrong types. What steps will you follow to clean it?

When faced with messy data containing missing values, duplicates, and wrong data types, I would follow these systematic steps to clean it:

1.  **Understand the Data:**
    *   **Load the Data:** Load the data into a suitable structure (e.g., pandas DataFrame).
    *   **Initial Inspection:** Use `df.head()`, `df.tail()`, `df.sample()` to get a quick overview.
    *   **Check Data Types:** Use `df.info()` or `df.dtypes` to understand current data types and identify immediate mismatches.
    *   **Summary Statistics:** Use `df.describe()` for numerical columns and `df.describe(include='object')` for categorical columns to understand distributions and potential issues.

2.  **Handle Missing Values (Imputation/Removal):**
    *   **Identify Missing Values:** Use `df.isnull().sum()` to count missing values per column and `df.isnull().sum() / len(df) * 100` to get percentages.
    *   **Visualize Missing Data:** Use heatmaps (e.g., `seaborn.heatmap(df.isnull())`) to visualize patterns of missingness.
    *   **Strategy for Numerical Columns:**
        *   **Imputation:** Fill with mean, median (less sensitive to outliers), or mode. This depends on the distribution and domain knowledge.
        *   **Prediction:** Use machine learning models (e.g., K-Nearest Neighbors Imputer) for more sophisticated imputation.
    *   **Strategy for Categorical Columns:**
        *   **Imputation:** Fill with mode, a 'Missing' category, or based on other column values.
    *   **Removal:** If a column has a very high percentage of missing values (e.g., >70-80%), or if specific rows have too many missing values and are not salvageable, consider dropping those columns or rows, respectively.
    *   **Forward/Backward Fill:** For time-series data, use `ffill()` or `bfill()`.

3.  **Correct Data Types:**
    *   **Convert Types:** Use `df['column'].astype(new_type)` or `pd.to_datetime()`, `pd.to_numeric()`, `pd.Categorical()`.
    *   **Handle Errors during Conversion:** Use `errors='coerce'` in `pd.to_numeric` or `pd.to_datetime` to convert problematic values into `NaN`, which can then be handled as missing values.

4.  **Remove Duplicate Records:**
    *   **Identify Duplicates:** Use `df.duplicated().sum()` to count full-row duplicates.
    *   **Remove Duplicates:** Use `df.drop_duplicates(inplace=True)`. Consider `subset` parameter if duplicates should be identified based on a specific set of columns.

5.  **Address Inconsistent Data Entry and Standardization:**
    *   **Categorical Data:** Look for variations of the same category (e.g., 'USA', 'U.S.A.', 'United States'). Standardize them to a single representation using `replace()` or mapping.
    *   **Text Data:** Convert text to lowercase, remove extra spaces, special characters, and apply stemming/lemmatization if necessary for natural language processing tasks.
    *   **Units and Formats:** Ensure consistent units (e.g., all monetary values in USD, all temperatures in Celsius) and date formats.

6.  **Handle Outliers (Optional, Context-Dependent):**
    *   **Identify Outliers:** Use visualizations (box plots, scatter plots, histograms), statistical methods (Z-score, IQR method), or domain knowledge.
    *   **Strategy:**
        *   **Removal:** Remove outliers if they are clearly data entry errors or extreme values that would skew analysis.
        *   **Transformation:** Apply log transformation or square root transformation to reduce the impact of skewness caused by outliers.
        *   **Imputation:** Treat outliers as missing values and impute them.
        *   **Capping/Flooring:** Replace extreme values with a certain percentile value.

7.  **Data Validation and Verification:**
    *   **Cross-check with Business Rules:** Ensure the cleaned data adheres to known business rules and constraints.
    *   **Spot Checks:** Manually inspect a sample of the cleaned data.
    *   **Re-run Summary Statistics:** Check `df.info()` and `df.describe()` again to confirm the cleaning steps were successful.

### 3. How can you check column names, data types, and summary statistics? What does "info()" show that "describe()" does not?

To check column names, data types, and summary statistics in pandas:

*   **Column Names:**
    *   `df.columns`: Returns an Index object containing all column names.
    *   `df.columns.tolist()`: Converts column names to a list.

*   **Data Types:**
    *   `df.dtypes`: Returns a Series with the data type of each column.
    *   `df.info()`: Provides a concise summary of the DataFrame, including data types for each column, non-null counts, and memory usage.

*   **Summary Statistics:**
    *   `df.describe()`: Generates descriptive statistics for numerical columns (count, mean, std, min, 25%, 50%, 75%, max).
    *   `df.describe(include='object')`: Generates descriptive statistics for categorical/object columns (count, unique, top, freq).
    *   `df.describe(include='all')`: Generates descriptive statistics for all columns, including both numerical and categorical, where applicable.

#### What `df.info()` shows that `df.describe()` does not:

`df.info()` and `df.describe()` serve different but complementary purposes.

`df.info()` provides a high-level overview of the DataFrame's structure and health, specifically showing:

1.  **Non-Null Counts:** For each column, `info()` tells you the number of non-null (non-missing) entries. This is extremely valuable for quickly identifying columns with missing values and understanding their extent without needing to calculate `isnull().sum()`. `describe()` does show `count` for numerical columns, which is the number of non-null values, but `info()` provides this for **all** column types.
2.  **Memory Usage:** It reports the approximate memory usage of the DataFrame. This is crucial for performance optimization, especially with large datasets, as it helps in understanding the memory footprint of different data types.
3.  **DataFrame Index Type and Entries:** It displays the type of the index (e.g., `RangeIndex`) and the number of entries, indicating the total number of rows.
4.  **Column Names and Data Types at a glance:** While `df.dtypes` gives data types, `df.info()` presents them alongside column names and non-null counts in a very readable format, making it easy to grasp the overall structure quickly.

In contrast, `df.describe()` focuses purely on **statistical summaries** of the data within the columns, giving insights into central tendency, dispersion, and shape of the distribution, but it doesn't provide information about missing value counts across all types, or memory usage.

### 4. How do you identify missing values and outliers in a dataset?

#### Identifying Missing Values:

Missing values are common in real-world datasets and need to be identified before they can be handled. Here are common methods:

1.  **Count Missing Values per Column:**
    *   `df.isnull().sum()`: This is the most common and effective way. It returns a Series showing the count of `True` values (i.e., `NaN`, `None`, `NaT`) for each column.
    *   `df.isna().sum()`: `isna()` is an alias for `isnull()`, so it works the same way.

2.  **Calculate Percentage of Missing Values:**
    *   `df.isnull().sum() / len(df) * 100`: This provides the percentage of missing values per column, which helps prioritize columns for imputation or removal.

3.  **Visualize Missing Data:**
    *   **Heatmap (`seaborn.heatmap`):** A heatmap of `df.isnull()` or `df.isna()` can visually represent the distribution of missing values across the DataFrame. Darker areas often indicate missingness. This is good for spotting patterns (e.g., missing values always occurring together).
    *   **Missingno Library:** The `missingno` library (`msno`) provides powerful visualizations like `msno.matrix()`, `msno.bar()`, `msno.heatmap()`, and `msno.dendrogram()` to understand missingness patterns and correlations.

4.  **Check for Any Missing Values:**
    *   `df.isnull().any()`: Returns a Series indicating whether each column has *any* missing values (`True` or `False`).
    *   `df.isnull().sum().sum()`: Returns the total number of missing values in the entire DataFrame.

5.  **Identify Rows with Missing Values:**
    *   `df[df.isnull().any(axis=1)]`: Filters the DataFrame to show all rows that contain at least one missing value.

#### Identifying Outliers:

Outliers are data points that significantly deviate from other observations. They can be errors or genuine extreme values. Identifying them is crucial as they can skew statistical analyses and machine learning models. Here are common methods:

1.  **Statistical Methods:**
    *   **Z-score:** For normally distributed data, a Z-score measures how many standard deviations an element is from the mean. Values with an absolute Z-score greater than 2, 2.5, or 3 (depending on the threshold chosen) are often considered outliers. Calculated as `(x - mean) / std_dev`.
        ```python
        from scipy.stats import zscore
        df['zscore'] = np.abs(zscore(df['numerical_column']))
        outliers = df[df['zscore'] > 3]
        ```
    *   **Interquartile Range (IQR):** This method is robust to non-normal distributions. It defines outliers as values falling below `Q1 - 1.5 * IQR` or above `Q3 + 1.5 * IQR`, where Q1 is the 25th percentile, Q3 is the 75th percentile, and IQR = Q3 - Q1.
        ```python
        Q1 = df['numerical_column'].quantile(0.25)
        Q3 = df['numerical_column'].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR
        outliers = df[(df['numerical_column'] < lower_bound) | (df['numerical_column'] > upper_bound)]
        ```

2.  **Visual Methods:**
    *   **Box Plots:** Display the distribution of data and clearly show outliers as individual points beyond the whiskers (which typically extend to 1.5 * IQR from the quartiles).
        ```python
        import seaborn as sns
        sns.boxplot(y=df['numerical_column'])
        ```
    *   **Histograms:** Can reveal extreme values in the tails of the distribution.
        ```python
        df['numerical_column'].hist()
        ```
    *   **Scatter Plots:** For bivariate analysis, scatter plots can identify outliers that deviate significantly from the main cluster of data points.
        ```python
        sns.scatterplot(x='col_x', y='col_y', data=df)
        ```

3.  **Machine Learning-Based Methods:**
    *   **Isolation Forest:** An unsupervised algorithm that isolates anomalies by randomly selecting a feature and then randomly selecting a split value between the maximum and minimum values of the selected feature. The number of splits required to isolate a sample is equivalent to the path length from the root node to the terminating node.
    *   **Local Outlier Factor (LOF):** Measures the local deviation of density of a given sample with respect to its neighbors. It considers as outliers samples that have a substantially lower density than their neighbors.
    *   **One-Class SVM:** An unsupervised algorithm for novelty detection, where it learns a decision function for a given data set to detect new or anomalous observations.

The choice of method depends on the data distribution, the definition of an outlier in the specific context, and the overall goal of the analysis.

### 5. How do you reduce memory usage in pandas DataFrames?

Reducing memory usage in pandas DataFrames is crucial, especially when working with large datasets that might exceed available RAM, leading to slower performance or even crashes. Here's a long answer detailing various techniques:

#### 1. Choose Appropriate Data Types:

This is often the most impactful way to reduce memory usage. Pandas defaults to `int64` and `float64` for numerical data, and `object` for strings, which are often overkill.

*   **Integers (`int`):**
    *   If you know the range of your integer data, use smaller integer types: `int8`, `int16`, `int32` instead of `int64`.
    *   For example, if a column only contains values between 0 and 255, `uint8` (unsigned 8-bit integer) is sufficient.
    ```python
    df['small_int_column'] = df['small_int_column'].astype('int8')
    ```

*   **Floats (`float`):**
    *   Similarly, if precision is not paramount, use `float32` instead of `float64`.
    ```python
    df['float_column'] = df['float_column'].astype('float32')
    ```

*   **Categorical Data (`object` to `category`):**
    *   This is extremely effective for columns with a limited number of unique string values (e.g., 'Gender', 'City', 'Product Type'). Converting an `object` column to `category` stores the unique values once and uses integer pointers to them, drastically reducing memory.
    ```python
    df['categorical_column'] = df['categorical_column'].astype('category')
    ```

*   **Booleans (`object` to `bool`):**
    *   Ensure columns containing only `True`/`False` values are stored as `bool` (1 byte per value) instead of `object` (which can be much larger).
    ```python
    df['boolean_column'] = df['boolean_column'].astype('bool')
    ```

*   **Dates and Times (`object` to `datetime`):**
    *   If a column stores dates or timestamps as strings, convert it to `datetime64[ns]` using `pd.to_datetime()`. This is more memory-efficient than `object` for dates and enables time-series operations.
    ```python
    df['date_column'] = pd.to_datetime(df['date_column'])
    ```

#### 2. Read Data Efficiently:

*   **Specify `dtype` during `read_csv()`:** Instead of letting pandas infer types (which can lead to `object` types or larger numerical types), provide a `dtype` dictionary when loading data.
    ```python
    dtype = {'col1': 'int16', 'col2': 'category', 'col3': 'float32'}
    df = pd.read_csv('your_file.csv', dtype=dtype)
    ```
*   **Use `chunksize`:** For very large files that don't fit into memory, read them in chunks, process each chunk, and then concatenate or aggregate the results.
    ```python
    chunks = pd.read_csv('large_file.csv', chunksize=10000)
    processed_chunks = []
    for chunk in chunks:
        # Process chunk (e.g., reduce types, filter rows)
        processed_chunks.append(chunk)
    df = pd.concat(processed_chunks)
    ```
*   **Select only necessary columns:** If you don't need all columns, use the `usecols` parameter in `read_csv()`.
    ```python
    df = pd.read_csv('your_file.csv', usecols=['col1', 'col2'])
    ```

#### 3. Optimize String Storage:

*   **Categorical Type:** As mentioned, `category` is the best for strings with low cardinality.
*   **StringDtype:** For string columns that don't benefit from `category` (e.g., high cardinality, unique identifiers), pandas 1.0+ introduced `StringDtype` (`pd.StringDtype()`). This is more memory-efficient than the generic `object` dtype, especially for short strings, as it uses an internal array of Python strings rather than individual Python string objects.
    ```python
    df['high_cardinality_string'] = df['high_cardinality_string'].astype(pd.StringDtype())
    ```

#### 4. Delete Unnecessary Objects and Free Memory:

*   **Delete variables:** Remove DataFrames or Series that are no longer needed using `del`.
    ```python
    del old_df
    ```
*   **Force garbage collection:** Occasionally, Python's garbage collector might not immediately free up memory. You can explicitly call it:
    ```python
    import gc
    gc.collect()
    ```

#### 5. Downcasting Numerical Data:

You can write a function to automatically downcast numerical columns to their smallest possible type without losing information.

```python
def reduce_mem_usage(df, verbose=True):
    numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
    start_mem = df.memory_usage().sum() / 1024**2
    for col in df.columns:
        col_type = df[col].dtypes
        if col_type in numerics:
            c_min = df[col].min()
            c_max = df[col].max()
            if str(col_type)[:3] == 'int':
                if c_min > np.iinfo(np.int8).min and c_max < np.iinfo(np.int8).max:
                    df[col] = df[col].astype(np.int8)
                elif c_min > np.iinfo(np.int16).min and c_max < np.iinfo(np.int16).max:
                    df[col] = df[col].astype(np.int16)
                elif c_min > np.iinfo(np.int32).min and c_max < np.iinfo(np.int32).max:
                    df[col] = df[col].astype(np.int32)
                else:
                    df[col] = df[col].astype(np.int64)
            else:
                if c_min > np.finfo(np.float16).min and c_max < np.finfo(np.float16).max:
                    df[col] = df[col].astype(np.float16)
                elif c_min > np.finfo(np.float32).min and c_max < np.finfo(np.float32).max:
                    df[col] = df[col].astype(np.float32)
                else:
                    df[col] = df[col].astype(np.float64)
    end_mem = df.memory_usage().sum() / 1024**2
    if verbose: print(f'Memory usage after optimization: {end_mem:.2f} MB (decreased by {(100 * (start_mem - end_mem) / start_mem):.1f}%)')
    return df

# Example usage:
# df = reduce_mem_usage(df)
```

#### 6. Use Sparse Data Structures:

*   If your DataFrame contains many zero or `NaN` values, pandas offers `SparseDtype` for Series and `SparseDataFrame` (though `SparseDataFrame` is deprecated in favor of `SparseArray` and `SparseDtype`). Storing data sparsely can save memory by only storing the non-zero/non-NaN values.
    ```python
    df['sparse_column'] = df['sparse_column'].astype(pd.SparseDtype("int", 0)) # for integer type with 0 as fill value
    ```

#### 7. Avoid Chaining Operations (and Create Copies Only When Necessary):

*   Chaining operations can sometimes create intermediate copies of DataFrames, consuming extra memory. Perform operations in-place or assign results to the same variable to avoid temporary copies where possible.
*   Be mindful of `.copy()` – only use it when you explicitly need a deep copy of a slice of the DataFrame; otherwise, view-based operations are more memory-efficient.

#### 8. Use Libraries Optimized for Large Datasets:

*   **Dask:** If a DataFrame truly becomes too large for pandas even after optimization, Dask provides DataFrame objects that mimic pandas but operate on out-of-core, parallelized data, allowing you to work with datasets larger than RAM.
*   **PySpark, Vaex:** Other libraries like Apache Spark (via PySpark) or Vaex are designed for large-scale data processing.

By systematically applying these techniques, you can significantly reduce the memory footprint of your pandas DataFrames, making your data analysis more efficient and manageable.

In [ ]:
Code:

## Pandas Data Wrangling Examples

In [ ]:
import pandas as pd
import numpy as np

# Create a sample DataFrame for demonstration
data = {
    'Student_ID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Heidi', 'Ivan', 'Judy'],
    'Score_Math': [85, 92, 78, 88, 95, 70, 81, 90, 76, 83],
    'Score_Science': [90, 88, 75, 85, 92, 72, 80, 87, 79, 81],
    'Grade': ['A', 'A', 'C', 'B', 'A', 'D', 'B', 'A', 'C', 'B'],
    'Attendance': [0.95, 0.98, 0.90, 0.92, 0.97, 0.88, 0.93, 0.96, 0.89, 0.94],
    'Status': ['Active', 'Active', 'Inactive', 'Active', 'Active', 'Active', 'Inactive', 'Active', 'Active', 'Active'],
    'Enrollment_Date': pd.to_datetime(['2023-09-01', '2023-09-01', '2023-09-05', '2023-09-02', '2023-09-01', '2023-09-03', '2023-09-06', '2023-09-02', '2023-09-04', '2023-09-01'])
}
df = pd.DataFrame(data)

df_extended = pd.DataFrame({
    'Student_ID': [1, 2, 11, 4, 12],
    'Address': ['123 Main St', '456 Oak Ave', '789 Pine Rd', '101 Elm St', '202 Birch Ln'],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']
})

print("Original DataFrame:")
display(df.head())
print("Extended DataFrame (for merge/join):")
display(df_extended.head())

Original DataFrame:

,Student_ID,Name,Score_Math,Score_Science,Grade,Attendance,Status,Enrollment_Date
0,1,Alice,85,90,A,0.95,Active,2023-09-01
1,2,Bob,92,88,A,0.98,Active,2023-09-01
2,3,Charlie,78,75,C,0.90,Inactive,2023-09-05
3,4,David,88,85,B,0.92,Active,2023-09-02
4,5,Eve,95,92,A,0.97,Active,2023-09-01

Extended DataFrame (for merge/join):

   Student_ID       Address         City
0           1   123 Main St     New York
1           2   456 Oak Ave  Los Angeles
2          11   789 Pine Rd      Chicago
3           4    101 Elm St      Houston
4          12  202 Birch Ln      Phoenix

## Weak Students (Basic)

### 1. Select a single column from a DataFrame.

In [ ]:
# Select the 'Name' column
name_column = df['Name']
print("Selected 'Name' column (Series):")
display(name_column.head())

Selected 'Name' column (Series):

0      Alice
1        Bob
2    Charlie
3      David
4        Eve
Name: Name, dtype: object

### 2. Add a new column with constant values.

In [ ]:
# Add a new column 'Year' with a constant value
df['Year'] = 2023
print("DataFrame with 'Year' column:")
display(df.head())

DataFrame with 'Year' column:

,Student_ID,Name,Score_Math,Score_Science,Grade,Attendance,Status,Enrollment_Date,Year
0,1,Alice,85,90,A,0.95,Active,2023-09-01,2023
1,2,Bob,92,88,A,0.98,Active,2023-09-01,2023
2,3,Charlie,78,75,C,0.90,Inactive,2023-09-05,2023
3,4,David,88,85,B,0.92,Active,2023-09-02,2023
4,5,Eve,95,92,A,0.97,Active,2023-09-01,2023

### 3. Sort a DataFrame by one column.

In [ ]:
# Sort the DataFrame by 'Score_Math' in ascending order
sorted_df = df.sort_values(by='Score_Math', ascending=True)
print("DataFrame sorted by 'Score_Math':")
display(sorted_df.head())

DataFrame sorted by 'Score_Math':

,Student_ID,Name,Score_Math,Score_Science,Grade,Attendance,Status,Enrollment_Date,Year
5,6,Frank,70,72,D,0.88,Active,2023-09-03,2023
8,9,Ivan,76,79,C,0.89,Active,2023-09-04,2023
2,3,Charlie,78,75,C,0.90,Inactive,2023-09-05,2023
6,7,Grace,81,80,B,0.93,Inactive,2023-09-06,2023
9,10,Judy,83,81,B,0.94,Active,2023-09-01,2023

### 4. Rename DataFrame columns.

In [ ]:
# Rename 'Score_Math' to 'Math_Score' and 'Score_Science' to 'Science_Score'
renamed_df = df.rename(columns={'Score_Math': 'Math_Score', 'Score_Science': 'Science_Score'})
print("DataFrame with renamed columns:")
display(renamed_df.head())

DataFrame with renamed columns:

,Student_ID,Name,Math_Score,Science_Score,Grade,Attendance,Status,Enrollment_Date,Year
0,1,Alice,85,90,A,0.95,Active,2023-09-01,2023
1,2,Bob,92,88,A,0.98,Active,2023-09-01,2023
2,3,Charlie,78,75,C,0.90,Inactive,2023-09-05,2023
3,4,David,88,85,B,0.92,Active,2023-09-02,2023
4,5,Eve,95,92,A,0.97,Active,2023-09-01,2023

### 5. Display summary statistics using describe().

In [ ]:
# Display summary statistics for numerical columns
print("Summary statistics for numerical columns:")
display(df.describe())

# Display summary statistics for all columns including categorical
print("Summary statistics for all columns:")
display(df.describe(include='all'))

Summary statistics for numerical columns:

,Student_ID,Score_Math,Score_Science,Attendance,Enrollment_Date,Year
count,10.00000,10.000000,10.000000,10.000000,10,10.0
mean,5.50000,83.800000,82.900000,0.932000,2023-09-02 14:24:00,2023.0
min,1.00000,70.000000,72.000000,0.880000,2023-09-01 00:00:00,2023.0
25%,3.25000,78.750000,79.250000,0.905000,2023-09-01 00:00:00,2023.0
50%,5.50000,84.000000,83.000000,0.935000,2023-09-02 00:00:00,2023.0
75%,7.75000,89.500000,87.750000,0.957500,2023-09-03 18:00:00,2023.0
max,10.00000,95.000000,92.000000,0.980000,2023-09-06 00:00:00,2023.0
std,3.02765,7.771744,6.573516,0.034254,NaN,0.0

Summary statistics for all columns:

,Student_ID,Name,Score_Math,Score_Science,Grade,Attendance,Status,Enrollment_Date,Year
count,10.00000,10,10.000000,10.000000,10,10.000000,10,10,10.0
unique,NaN,10,NaN,NaN,4,NaN,2,NaN,NaN
top,NaN,Alice,NaN,NaN,A,NaN,Active,NaN,NaN
freq,NaN,1,NaN,NaN,4,NaN,8,NaN,NaN
mean,5.50000,NaN,83.800000,82.900000,NaN,0.932000,NaN,2023-09-02 14:24:00,2023.0
min,1.00000,NaN,70.000000,72.000000,NaN,0.880000,NaN,2023-09-01 00:00:00,2023.0
25%,3.25000,NaN,78.750000,79.250000,NaN,0.905000,NaN,2023-09-01 00:00:00,2023.0
50%,5.50000,NaN,84.000000,83.000000,NaN,0.935000,NaN,2023-09-02 00:00:00,2023.0
75%,7.75000,NaN,89.500000,87.750000,NaN,0.957500,NaN,2023-09-03 18:00:00,2023.0
max,10.00000,NaN,95.000000,92.000000,NaN,0.980000,NaN,2023-09-06 00:00:00,2023.0
std,3.02765,NaN,7.771744,6.573516,NaN,0.034254,NaN,NaN,0.0

## Normal Students (Moderate)

### 6. Filter rows using multiple conditions.

In [ ]:
# Filter students with Math score > 80 AND Grade is 'A'
filtered_df = df[(df['Score_Math'] > 80) & (df['Grade'] == 'A')]
print("Students with Math Score > 80 and Grade 'A':")
display(filtered_df)

Students with Math Score > 80 and Grade 'A':

,Student_ID,Name,Score_Math,Score_Science,Grade,Attendance,Status,Enrollment_Date,Year
0,1,Alice,85,90,A,0.95,Active,2023-09-01,2023
1,2,Bob,92,88,A,0.98,Active,2023-09-01,2023
4,5,Eve,95,92,A,0.97,Active,2023-09-01,2023
7,8,Heidi,90,87,A,0.96,Active,2023-09-02,2023

### 7. Group data by a categorical column and calculate mean.

In [ ]:
# Group by 'Grade' and calculate the mean of 'Score_Math' and 'Score_Science'
mean_scores_by_grade = df.groupby('Grade')[['Score_Math', 'Score_Science']].mean()
print("Mean scores by Grade:")
display(mean_scores_by_grade)

Mean scores by Grade:

       Score_Math  Score_Science
Grade
A            90.5          89.25
B            84.0          82.00
C            77.0          77.00
D            70.0          72.00

### 8. Merge two DataFrames on a common column.

In [ ]:
# Merge 'df' and 'df_extended' on 'Student_ID'
merged_df = pd.merge(df, df_extended, on='Student_ID', how='left')
print("Merged DataFrame (left merge on Student_ID):")
display(merged_df)

Merged DataFrame (left merge on Student_ID):

,Student_ID,Name,Score_Math,Score_Science,Grade,Attendance,Status,Enrollment_Date,Year,Address,City
0,1,Alice,85,90,A,0.95,Active,2023-09-01,2023,123 Main St,New York
1,2,Bob,92,88,A,0.98,Active,2023-09-01,2023,456 Oak Ave,Los Angeles
2,3,Charlie,78,75,C,0.90,Inactive,2023-09-05,2023,NaN,NaN
3,4,David,88,85,B,0.92,Active,2023-09-02,2023,101 Elm St,Houston
4,5,Eve,95,92,A,0.97,Active,2023-09-01,2023,NaN,NaN
5,6,Frank,70,72,D,0.88,Active,2023-09-03,2023,NaN,NaN
6,7,Grace,81,80,B,0.93,Inactive,2023-09-06,2023,NaN,NaN
7,8,Heidi,90,87,A,0.96,Active,2023-09-02,2023,NaN,NaN
8,9,Ivan,76,79,C,0.89,Active,2023-09-04,2023,NaN,NaN
9,10,Judy,83,81,B,0.94,Active,2023-09-01,2023,NaN,NaN

### 9. Drop rows and columns using pandas functions.

In [ ]:
# Drop the 'Year' column (if added in a previous step)
df_dropped_col = df.drop(columns=['Year'], errors='ignore') # errors='ignore' prevents error if 'Year' doesn't exist
print("DataFrame after dropping 'Year' column:")
display(df_dropped_col.head())

# Drop rows where 'Status' is 'Inactive'
df_dropped_rows = df_dropped_col[df_dropped_col['Status'] != 'Inactive']
print("DataFrame after dropping 'Inactive' status rows:")
display(df_dropped_rows)

DataFrame after dropping 'Year' column:

,Student_ID,Name,Score_Math,Score_Science,Grade,Attendance,Status,Enrollment_Date
0,1,Alice,85,90,A,0.95,Active,2023-09-01
1,2,Bob,92,88,A,0.98,Active,2023-09-01
2,3,Charlie,78,75,C,0.90,Inactive,2023-09-05
3,4,David,88,85,B,0.92,Active,2023-09-02
4,5,Eve,95,92,A,0.97,Active,2023-09-01

DataFrame after dropping 'Inactive' status rows:

,Student_ID,Name,Score_Math,Score_Science,Grade,Attendance,Status,Enrollment_Date
0,1,Alice,85,90,A,0.95,Active,2023-09-01
1,2,Bob,92,88,A,0.98,Active,2023-09-01
3,4,David,88,85,B,0.92,Active,2023-09-02
4,5,Eve,95,92,A,0.97,Active,2023-09-01
5,6,Frank,70,72,D,0.88,Active,2023-09-03
7,8,Heidi,90,87,A,0.96,Active,2023-09-02
8,9,Ivan,76,79,C,0.89,Active,2023-09-04
9,10,Judy,83,81,B,0.94,Active,2023-09-01

### 10. Apply a simple function to a column.

In [ ]:
# Apply a function to calculate a weighted average score
df['Weighted_Score'] = df.apply(lambda row: (row['Score_Math'] * 0.6 + row['Score_Science'] * 0.4), axis=1)
print("DataFrame with 'Weighted_Score' column:")
display(df.head())

DataFrame with 'Weighted_Score' column:

,Student_ID,Name,Score_Math,Score_Science,Grade,Attendance,Status,Enrollment_Date,Year,Weighted_Score
0,1,Alice,85,90,A,0.95,Active,2023-09-01,2023,87.0
1,2,Bob,92,88,A,0.98,Active,2023-09-01,2023,90.4
2,3,Charlie,78,75,C,0.90,Inactive,2023-09-05,2023,76.8
3,4,David,88,85,B,0.92,Active,2023-09-02,2023,86.8
4,5,Eve,95,92,A,0.97,Active,2023-09-01,2023,93.8

## Bright Students (Advanced)

### 11. Perform pivot and melt operations on a dataset.

In [ ]:
# Pivot operation
# Let's create a simpler DataFrame for pivoting to show student scores by subject.
pivot_data = {
    'Student_ID': [1, 1, 2, 2, 3, 3],
    'Subject': ['Math', 'Science', 'Math', 'Science', 'Math', 'Science'],
    'Score': [85, 90, 92, 88, 78, 75]
}
df_pivot_melt = pd.DataFrame(pivot_data)

pivoted_df = df_pivot_melt.pivot_table(index='Student_ID', columns='Subject', values='Score')
print("Pivoted DataFrame (Student_ID as index, Subjects as columns, Scores as values):")
display(pivoted_df)

# Melt operation
melted_df = pd.melt(pivoted_df.reset_index(), id_vars=['Student_ID'], var_name='Subject', value_name='Score')
print("Melted DataFrame (back to long format):")
display(melted_df)

Pivoted DataFrame (Student_ID as index, Subjects as columns, Scores as values):

Subject     Math  Science
Student_ID
1           85.0     90.0
2           92.0     88.0
3           78.0     75.0

Melted DataFrame (back to long format):

   Student_ID  Subject  Score
0           1     Math   85.0
1           2     Math   92.0
2           3     Math   78.0
3           1  Science   90.0
4           2  Science   88.0
5           3  Science   75.0

### 12. Implement multilevel indexing.

In [ ]:
# Create a DataFrame with multi-level index
df_multi_index = df.set_index(['Grade', 'Status'])
# Sort the index to improve performance and avoid PerformanceWarning
df_multi_index = df_multi_index.sort_index()
print("DataFrame with MultiIndex on 'Grade' and 'Status':")
display(df_multi_index.head())

# Access data using multi-level index (e.g., all 'Active' students with 'A' grade)
print("Accessing data for ('A', 'Active'):")
display(df_multi_index.loc[('A', 'Active')])

# Grouping with multi-level index
print("Mean Math Score by Grade and Status:")
display(df.groupby(['Grade', 'Status'])['Score_Math'].mean())

DataFrame with MultiIndex on 'Grade' and 'Status':

              Student_ID   Name  Score_Math  Score_Science  Attendance  \
Grade Status
A     Active           1  Alice          85             90        0.95
      Active           2    Bob          92             88        0.98
      Active           5    Eve          95             92        0.97
      Active           8  Heidi          90             87        0.96
B     Active           4  David          88             85        0.92

             Enrollment_Date  Year  Weighted_Score
Grade Status
A     Active      2023-09-01  2023            87.0
      Active      2023-09-01  2023            90.4
      Active      2023-09-01  2023            93.8
      Active      2023-09-02  2023            88.8
B     Active      2023-09-02  2023            86.8

Accessing data for ('A', 'Active'):

              Student_ID   Name  Score_Math  Score_Science  Attendance  \
Grade Status
A     Active           1  Alice          85             90        0.95
      Active           2    Bob          92             88        0.98
      Active           5    Eve          95             92        0.97
      Active           8  Heidi          90             87        0.96

             Enrollment_Date  Year  Weighted_Score
Grade Status
A     Active      2023-09-01  2023            87.0
      Active      2023-09-01  2023            90.4
      Active      2023-09-01  2023            93.8
      Active      2023-09-02  2023            88.8

Mean Math Score by Grade and Status:

Grade  Status
A      Active      90.5
B      Active      85.5
       Inactive    81.0
C      Active      76.0
       Inactive    78.0
D      Active      70.0
Name: Score_Math, dtype: float64

### 13. Compare merge v/s join operations.

In [ ]:
# DataFrames for demonstration
# df already exists
# df_extended already exists

print("Original df:")
display(df[['Student_ID', 'Name', 'Score_Math']].head())
print("Original df_extended:")
display(df_extended.head())

# --- MERGE ---
# pd.merge() is a standalone function that can merge DataFrames based on columns or indices.
# It's more flexible and is the recommended way for most merging operations.
merged_df_example = pd.merge(df, df_extended, on='Student_ID', how='inner')
print("\n--- Using pd.merge (inner join on 'Student_ID') ---")
print("Combines based on 'Student_ID' column. Handles overlapping column names by adding suffixes (e.g., '_x', '_y').")
display(merged_df_example)

# --- JOIN ---
# df.join() is a DataFrame method that joins DataFrames based on their indexes by default.
# It can join on a column by setting 'on' parameter, but the *other* DataFrame still uses its index.

# To use join, we often need to set an index first.
df_indexed = df.set_index('Student_ID')
df_extended_indexed = df_extended.set_index('Student_ID')

joined_df_example = df_indexed.join(df_extended_indexed, how='inner')
print("\n--- Using df.join (inner join on index) ---")
print("Combines based on index. If columns overlap, it will raise an error unless suffixes are specified.")
display(joined_df_example)

print("\n--- Key Differences ---")
print("1. **Function vs. Method**: `pd.merge()` is a function, `df.join()` is a method.")
print("2. **Default Join Key**: `merge` defaults to common columns, `join` defaults to index.")
print("3. **Flexibility**: `merge` is generally more flexible, allowing joining on multiple columns, different column names, etc.")
print("4. **Suffixes**: `merge` automatically handles overlapping column names with suffixes. `join` requires manual suffix specification or renaming for overlaps.")

Original df:

   Student_ID     Name  Score_Math
0           1    Alice          85
1           2      Bob          92
2           3  Charlie          78
3           4    David          88
4           5      Eve          95

Original df_extended:

   Student_ID       Address         City
0           1   123 Main St     New York
1           2   456 Oak Ave  Los Angeles
2          11   789 Pine Rd      Chicago
3           4    101 Elm St      Houston
4          12  202 Birch Ln      Phoenix

--- Using pd.merge (inner join on 'Student_ID') ---
Combines based on 'Student_ID' column. Handles overlapping column names by adding suffixes (e.g., '_x', '_y').

,Student_ID,Name,Score_Math,Score_Science,Grade,Attendance,Status,Enrollment_Date,Year,Weighted_Score,Address,City
0,1,Alice,85,90,A,0.95,Active,2023-09-01,2023,87.0,123 Main St,New York
1,2,Bob,92,88,A,0.98,Active,2023-09-01,2023,90.4,456 Oak Ave,Los Angeles
2,4,David,88,85,B,0.92,Active,2023-09-02,2023,86.8,101 Elm St,Houston

--- Using df.join (inner join on index) ---
Combines based on index. If columns overlap, it will raise an error unless suffixes are specified.

,Name,Score_Math,Score_Science,Grade,Attendance,Status,Enrollment_Date,Year,Weighted_Score,Address,City
Student_ID,,,,,,,,,,,
1,Alice,85,90,A,0.95,Active,2023-09-01,2023,87.0,123 Main St,New York
2,Bob,92,88,A,0.98,Active,2023-09-01,2023,90.4,456 Oak Ave,Los Angeles
4,David,88,85,B,0.92,Active,2023-09-02,2023,86.8,101 Elm St,Houston

--- Key Differences ---
1. **Function vs. Method**: `pd.merge()` is a function, `df.join()` is a method.
2. **Default Join Key**: `merge` defaults to common columns, `join` defaults to index.
3. **Flexibility**: `merge` is generally more flexible, allowing joining on multiple columns, different column names, etc.
4. **Suffixes**: `merge` automatically handles overlapping column names with suffixes. `join` requires manual suffix specification or renaming for overlaps.

### 14. Create custom aggregation functions.

In [ ]:
# Custom aggregation function: Range (max - min)
def score_range(series):
    return series.max() - series.min()

# Group by 'Grade' and apply custom aggregation for 'Score_Math' and built-in for 'Score_Science'
custom_agg_df = df.groupby('Grade').agg(
    Math_Score_Range=('Score_Math', score_range),
    Avg_Science_Score=('Score_Science', 'mean'),
    Count_Students=('Student_ID', 'count')
)

print("Custom aggregation by Grade:")
display(custom_agg_df)

Custom aggregation by Grade:

       Math_Score_Range  Avg_Science_Score  Count_Students
Grade
A                    10              89.25               4
B                     7              82.00               3
C                     2              77.00               2
D                     0              72.00               1

15. Perform time series based data wrangling.

In [ ]:
# Create a sample time-series DataFrame
ts_data = {
    'Date': pd.to_datetime(['2023-01-01', '2023-01-01', '2023-01-02', '2023-01-03', '2023-01-03', '2023-01-04', '2023-01-07', '2023-01-07']),
    'Sales': [100, 150, 200, 120, 180, 250, 300, 170],
    'City': ['A', 'B', 'A', 'A', 'B', 'A', 'A', 'B']
}
df_ts = pd.DataFrame(ts_data)

# 1. Set 'Date' as the index
df_ts = df_ts.set_index('Date')
print("Original Time-Series DataFrame (indexed by Date):")
display(df_ts)

# 2. Resample daily data to weekly, summing sales
# 'W' for weekly frequency, 'SM' for semi-monthly, 'M' for monthly, 'Q' for quarterly
weekly_sales = df_ts['Sales'].resample('W').sum()
print("\nWeekly Sales (summed):")
display(weekly_sales)

# 3. Calculate a 3-day rolling average of sales
# min_periods=1 allows calculation even if fewer than 3 periods are available at the start
df_ts['Sales_Rolling_Avg_3D'] = df_ts['Sales'].rolling(window='3D', min_periods=1).mean()
print("\nSales with 3-day Rolling Average:")
display(df_ts)

# 4. Forward fill missing dates (if any, after resampling)
# Create a daily range and reindex to explicitly show missing days
daily_range = pd.date_range(start=df_ts.index.min(), end=df_ts.index.max(), freq='D')
df_ts_reindexed = df_ts.reindex(daily_range)
print("\nTime-Series reindexed to daily with NaNs:")
display(df_ts_reindexed)

df_ts_ffill = df_ts_reindexed.ffill()
print("\nTime-Series after Forward Fill:")
display(df_ts_ffill)

# 5. Extract time-based features
df['Enrollment_Month'] = df['Enrollment_Date'].dt.month
df['Enrollment_DayOfWeek'] = df['Enrollment_Date'].dt.dayofweek
print("\nDataFrame with extracted time-based features (Month, DayOfWeek):")
display(df.head())

Original Time-Series DataFrame (indexed by Date):

            Sales City
Date
2023-01-01    100    A
2023-01-01    150    B
2023-01-02    200    A
2023-01-03    120    A
2023-01-03    180    B
2023-01-04    250    A
2023-01-07    300    A
2023-01-07    170    B

Weekly Sales (summed):

Date
2023-01-01     250
2023-01-08    1220
Freq: W-SUN, Name: Sales, dtype: int64

Sales with 3-day Rolling Average:

            Sales City  Sales_Rolling_Avg_3D
Date
2023-01-01    100    A                 100.0
2023-01-01    150    B                 125.0
2023-01-02    200    A                 150.0
2023-01-03    120    A                 142.5
2023-01-03    180    B                 150.0
2023-01-04    250    A                 187.5
2023-01-07    300    A                 300.0
2023-01-07    170    B                 235.0

ValueError: cannot reindex on an axis with duplicate labels

Conclusion:

This practical session effectively demonstrated the critical aspects of **data wrangling** using pandas, a fundamental skill for any data professional. We began by establishing a strong theoretical foundation, understanding why data wrangling is essential before analysis, how to approach messy datasets, and methods for inspecting DataFrame properties.

Through a series of practical examples, categorized by complexity, we covered:

*   **Basic Operations:** Selecting columns, adding new columns, sorting, renaming columns, and obtaining summary statistics.
*   **Moderate Operations:** Filtering data with multiple conditions, grouping data for aggregation, merging DataFrames, dropping unwanted rows and columns, and applying custom functions.
*   **Advanced Operations:** Reshaping data using pivot and melt, implementing multilevel indexing for complex data structures, comparing `merge` and `join` operations, creating custom aggregation functions, and performing time-series specific wrangling tasks like resampling, calculating rolling averages, and extracting time-based features.

Each example showcased specific pandas functionalities, highlighting their utility in cleaning, transforming, and preparing data for subsequent analysis or machine learning tasks. Mastering these techniques ensures data quality, improves usability, and ultimately leads to more reliable and insightful conclusions.